/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BODY;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import user.Connect;
import user.DatabaseConnection;

/**
 *
 * @author HP
 */
public class getPassword extends javax.swing.JFrame {

    public getPassword() {
        initComponents();
        setLocationRelativeTo(null);
        //setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Content = new javax.swing.JPanel();
        lblTaiKhoan = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        lblNhapLaiMatKhau = new javax.swing.JLabel();
        panelTaiKhoan = new javax.swing.JPanel();
        iconUsername = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        panelMatKhau = new javax.swing.JPanel();
        iconPassword = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        panelNhapLaiMatKhau = new javax.swing.JPanel();
        iconPassword1 = new javax.swing.JLabel();
        txtNhapLaiMatKhau = new javax.swing.JPasswordField();
        jCheckBox2 = new javax.swing.JCheckBox();
        Bottom = new javax.swing.JPanel();
        btnLogin = new BODY.Button.ButtonLogin();
        lblLogin = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblReg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 216, 224));

        Main.setBackground(new java.awt.Color(204, 216, 224));
        Main.setPreferredSize(new java.awt.Dimension(500, 700));
        Main.setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(204, 216, 224));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBackground(new java.awt.Color(255, 255, 255));
        Title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("ĐẶT LẠI MẬT KHẨU");
        Header.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 100));

        jSeparator1.setBackground(new java.awt.Color(0, 120, 255));
        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator1.setOpaque(true);
        Header.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 75, 190, 5));

        Main.add(Header, java.awt.BorderLayout.PAGE_START);

        Content.setBackground(new java.awt.Color(204, 216, 224));
        Content.setBorder(null);
        Content.setPreferredSize(new java.awt.Dimension(500, 280));
        Content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTaiKhoan.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblTaiKhoan.setText("Email hoặc Số điện thoại");
        Content.add(lblTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 200, 35));

        lblMatKhau.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblMatKhau.setText("Mật khẩu mới");
        Content.add(lblMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 125, 120, 35));

        lblNhapLaiMatKhau.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblNhapLaiMatKhau.setText("Nhập lại mật khẩu");
        Content.add(lblNhapLaiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 255, 150, 35));

        panelTaiKhoan.setLayout(new java.awt.BorderLayout());

        iconUsername.setBackground(new java.awt.Color(153, 153, 153));
        iconUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/5402435_account_profile_user_avatar_man_icon.png"))); // NOI18N
        iconUsername.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        iconUsername.setOpaque(true);
        iconUsername.setPreferredSize(new java.awt.Dimension(40, 40));
        panelTaiKhoan.add(iconUsername, java.awt.BorderLayout.WEST);

        txtTaiKhoan.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTaiKhoan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelTaiKhoan.add(txtTaiKhoan, java.awt.BorderLayout.CENTER);

        Content.add(panelTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 340, 40));

        panelMatKhau.setLayout(new java.awt.BorderLayout());

        iconPassword.setBackground(new java.awt.Color(153, 153, 153));
        iconPassword.setForeground(new java.awt.Color(153, 153, 153));
        iconPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/7491947_ui_key_password_lock_security_icon.png"))); // NOI18N
        iconPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        iconPassword.setOpaque(true);
        iconPassword.setPreferredSize(new java.awt.Dimension(40, 40));
        panelMatKhau.add(iconPassword, java.awt.BorderLayout.WEST);

        txtMatKhau.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtMatKhau.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelMatKhau.add(txtMatKhau, java.awt.BorderLayout.CENTER);

        Content.add(panelMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 165, 340, 40));

        jCheckBox1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCheckBox1.setText("Hiện mật khẩu");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        Content.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, 40));

        panelNhapLaiMatKhau.setLayout(new java.awt.BorderLayout());

        iconPassword1.setBackground(new java.awt.Color(153, 153, 153));
        iconPassword1.setForeground(new java.awt.Color(153, 153, 153));
        iconPassword1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPassword1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/7491947_ui_key_password_lock_security_icon.png"))); // NOI18N
        iconPassword1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        iconPassword1.setOpaque(true);
        iconPassword1.setPreferredSize(new java.awt.Dimension(40, 40));
        panelNhapLaiMatKhau.add(iconPassword1, java.awt.BorderLayout.WEST);

        txtNhapLaiMatKhau.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNhapLaiMatKhau.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelNhapLaiMatKhau.add(txtNhapLaiMatKhau, java.awt.BorderLayout.CENTER);

        Content.add(panelNhapLaiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 340, 40));

        jCheckBox2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCheckBox2.setText("Hiện mật khẩu");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        Content.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, 40));

        Main.add(Content, java.awt.BorderLayout.CENTER);

        Bottom.setBackground(new java.awt.Color(204, 216, 224));
        Bottom.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Bottom.setPreferredSize(new java.awt.Dimension(500, 220));
        Bottom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setText("HOÀN THÀNH");
        btnLogin.setToolTipText("");
        btnLogin.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        btnLogin.setRadius(50);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        Bottom.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 380, 50));

        lblLogin.setFont(new java.awt.Font("Dialog", 3, 16)); // NOI18N
        lblLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/7225775_arrow_login_icon.png"))); // NOI18N
        lblLogin.setText("Quay lại đăng nhập");
        lblLogin.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLoginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLoginMousePressed(evt);
            }
        });
        Bottom.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 100, 180, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 16)); // NOI18N
        jLabel5.setText("Bạn chưa có tài khoản ? Đăng ký");
        Bottom.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 250, 30));

        lblReg.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblReg.setForeground(new java.awt.Color(0, 0, 204));
        lblReg.setText("Tại đây");
        lblReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblRegMousePressed(evt);
            }
        });
        Bottom.add(lblReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 60, 30));

        Main.add(Bottom, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(Main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (txtTaiKhoan.getText().equals("") && txtMatKhau.getText().equals("") && txtNhapLaiMatKhau.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Tài khoản và mật khẩu không được để trống!");
        } else {
            if (!txtMatKhau.getText().equals(txtNhapLaiMatKhau.getText())) {
                JOptionPane.showMessageDialog(this, "Mật khẩu không khớp!");
            } else {
                try {
                    Connect a = new Connect();
                    Connection con = a.getConnection();
                    String url = "Update Nguoidung set MatKhau = '" + txtMatKhau.getText() + "' where TaiKhoan = '" + txtTaiKhoan.getText() + "'";
                    PreparedStatement pst = con.prepareStatement(url);
                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Đặt lại mật khẩu thành công!");
                    login g = new login();
                    g.setVisible(true); //để hiển thị màn hình form đăng nhập
                    setVisible(false); //thoát khỏi của sổ login
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            txtMatKhau.setEchoChar((char) 0);
        } else {
            txtMatKhau.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void lblRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegMouseClicked
        reg r = new reg();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblRegMouseClicked

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if (jCheckBox2.isSelected()) {
            txtNhapLaiMatKhau.setEchoChar((char) 0);
        } else {
            txtNhapLaiMatKhau.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        login r = new login();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblLoginMouseClicked

    private void lblLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseEntered
        lblLogin.setForeground(new Color(234, 67, 53));
    }//GEN-LAST:event_lblLoginMouseEntered

    private void lblLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseExited
        lblLogin.setForeground(Color.black);
    }//GEN-LAST:event_lblLoginMouseExited

    private void lblLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMousePressed
        lblLogin.setForeground(Color.blue);
    }//GEN-LAST:event_lblLoginMousePressed

    private void lblRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegMouseEntered
        lblReg.setForeground(new Color(234, 67, 53));
    }//GEN-LAST:event_lblRegMouseEntered

    private void lblRegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegMouseExited
        lblReg.setForeground(Color.blue);
    }//GEN-LAST:event_lblRegMouseExited

    private void lblRegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegMousePressed
        lblReg.setForeground(Color.black);
    }//GEN-LAST:event_lblRegMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(getPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(getPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(getPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new getPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bottom;
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Main;
    private javax.swing.JLabel Title;
    private BODY.Button.ButtonLogin btnLogin;
    private javax.swing.JLabel iconPassword;
    private javax.swing.JLabel iconPassword1;
    private javax.swing.JLabel iconUsername;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblNhapLaiMatKhau;
    private javax.swing.JLabel lblReg;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JPanel panelMatKhau;
    private javax.swing.JPanel panelNhapLaiMatKhau;
    private javax.swing.JPanel panelTaiKhoan;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JPasswordField txtNhapLaiMatKhau;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
