/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BODY;

import Manegement.panelData.HD;
import Manegement.panelData.LamKiemtra;
import Manegement.panelData.Hoc;
import Manegement.panelData.build;
import Manegement.panelData.home;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import user.Connect;

/**
 *
 * @author HP
 */
public class GUI extends javax.swing.JFrame {

    private JPanel childPanel;
    private JFrame frame;

    DefaultTableModel tbn = new DefaultTableModel();
    Connect a = new Connect();
    Connection con = a.getConnection();
    Statement st = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    String fPath = null;
    byte[] img_DATA;

    private String username;

    public GUI(String username) {
        initComponents();
        this.username = username;
        lblUsername.setText(username);
        this.setTitle("Phần Mềm Hỗ Trợ Bé Học Tiếng Anh");
        this.setLocationRelativeTo(null);

        childPanel = new home();
        MainRight.removeAll();
        MainRight.add(childPanel);
        MainRight.validate();

        btnHome.setBackground(new Color(255, 255, 102));
        btnHome.setForeground(Color.black);

        LabelLogo();
    }

    private GUI() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void LabelLogo() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Colorful Kids Learning Center Logo.png");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(400, 340, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lblLogo.setIcon(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        TopLeft = new javax.swing.JPanel();
        panelQuanLy = new javax.swing.JPanel();
        btnQuanLy = new BODY.Button.ButtonHome();
        jPanel5 = new javax.swing.JPanel();
        btnHuongDan = new BODY.Button.ButtonHome();
        TopRight = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        panelLogin = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        panelLogout = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        Main = new javax.swing.JPanel();
        MainLeft = new javax.swing.JPanel();
        MainLeftTop = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        MainLeftCenter = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        btnHome = new BODY.Button.ButtonHome();
        panelLearn = new javax.swing.JPanel();
        btnLearn = new BODY.Button.ButtonHome();
        panelQuiz = new javax.swing.JPanel();
        btnQuiz = new BODY.Button.ButtonHome();
        MainLeftBottom = new javax.swing.JPanel();
        MainRight = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jPanel1.setPreferredSize(new java.awt.Dimension(1700, 950));
        jPanel1.setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        Header.setPreferredSize(new java.awt.Dimension(1700, 70));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TopLeft.setBackground(new java.awt.Color(0, 0, 0));
        TopLeft.setOpaque(false);
        TopLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelQuanLy.setLayout(new java.awt.BorderLayout());

        btnQuanLy.setBackground(new java.awt.Color(255, 255, 255));
        btnQuanLy.setText("Quản lý");
        btnQuanLy.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        btnQuanLy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLyMouseClicked(evt);
            }
        });
        panelQuanLy.add(btnQuanLy, java.awt.BorderLayout.CENTER);

        TopLeft.add(panelQuanLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 50));

        jPanel5.setLayout(new java.awt.BorderLayout());

        btnHuongDan.setBackground(new java.awt.Color(255, 255, 255));
        btnHuongDan.setText("Hướng dẫn");
        btnHuongDan.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        btnHuongDan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHuongDanMouseClicked(evt);
            }
        });
        jPanel5.add(btnHuongDan, java.awt.BorderLayout.CENTER);

        TopLeft.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 170, 50));

        Header.add(TopLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 70));

        TopRight.setOpaque(false);
        TopRight.setPreferredSize(new java.awt.Dimension(250, 70));
        TopRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TopRight.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, 50));

        panelLogin.setBackground(new java.awt.Color(255, 255, 255));
        panelLogin.setBorder(null);
        panelLogin.setLayout(new java.awt.BorderLayout());

        lblLogin.setBackground(new java.awt.Color(255, 255, 255));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1564535_customer_user_userphoto_account_person_icon.png"))); // NOI18N
        lblLogin.setBorder(null);
        lblLogin.setOpaque(true);
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLoginMouseExited(evt);
            }
        });
        panelLogin.add(lblLogin, java.awt.BorderLayout.CENTER);

        TopRight.add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 50, 50));

        panelLogout.setBackground(new java.awt.Color(255, 255, 255));
        panelLogout.setBorder(null);
        panelLogout.setLayout(new java.awt.BorderLayout());

        lblLogout.setBackground(new java.awt.Color(255, 255, 255));
        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/48698_logout_icon.png"))); // NOI18N
        lblLogout.setBorder(null);
        lblLogout.setOpaque(true);
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });
        panelLogout.add(lblLogout, java.awt.BorderLayout.CENTER);

        TopRight.add(panelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 50, 50));

        Header.add(TopRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 0, 300, 70));

        jPanel1.add(Header, java.awt.BorderLayout.PAGE_START);

        Main.setLayout(new java.awt.BorderLayout());

        MainLeft.setBackground(new java.awt.Color(255, 255, 255));
        MainLeft.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(5, 10, 0, 10)));
        MainLeft.setPreferredSize(new java.awt.Dimension(300, 19));
        MainLeft.setLayout(new java.awt.BorderLayout(0, 10));

        MainLeftTop.setPreferredSize(new java.awt.Dimension(280, 300));
        MainLeftTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainLeftTop.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 276, 300));

        MainLeft.add(MainLeftTop, java.awt.BorderLayout.PAGE_START);

        MainLeftCenter.setBackground(new java.awt.Color(255, 255, 255));
        MainLeftCenter.setBorder(null);
        MainLeftCenter.setPreferredSize(new java.awt.Dimension(276, 300));
        MainLeftCenter.setLayout(new java.awt.GridLayout(4, 0, 0, 10));

        panelHome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelHome.setLayout(new java.awt.BorderLayout());

        btnHome.setBackground(new java.awt.Color(0, 102, 102));
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/4960719_home_mobile_ui_ux_web_icon.png"))); // NOI18N
        btnHome.setText("Trang chủ");
        btnHome.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnHome.setIconTextGap(30);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        panelHome.add(btnHome, java.awt.BorderLayout.CENTER);

        MainLeftCenter.add(panelHome);

        panelLearn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelLearn.setLayout(new java.awt.BorderLayout());

        btnLearn.setBackground(new java.awt.Color(0, 102, 102));
        btnLearn.setForeground(new java.awt.Color(255, 255, 255));
        btnLearn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/2064483_book_education_learn_student_study_icon.png"))); // NOI18N
        btnLearn.setText("Học từ vựng");
        btnLearn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnLearn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnLearn.setIconTextGap(30);
        btnLearn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLearnMouseClicked(evt);
            }
        });
        panelLearn.add(btnLearn, java.awt.BorderLayout.CENTER);

        MainLeftCenter.add(panelLearn);

        panelQuiz.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelQuiz.setLayout(new java.awt.BorderLayout());

        btnQuiz.setBackground(new java.awt.Color(0, 102, 102));
        btnQuiz.setForeground(new java.awt.Color(255, 255, 255));
        btnQuiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/2064476_education_learn_pencil_student_study_icon.png"))); // NOI18N
        btnQuiz.setText("Làm kiểm tra");
        btnQuiz.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnQuiz.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnQuiz.setIconTextGap(30);
        btnQuiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuizMouseClicked(evt);
            }
        });
        panelQuiz.add(btnQuiz, java.awt.BorderLayout.CENTER);

        MainLeftCenter.add(panelQuiz);

        MainLeft.add(MainLeftCenter, java.awt.BorderLayout.CENTER);

        MainLeftBottom.setBackground(new java.awt.Color(255, 255, 255));
        MainLeftBottom.setPreferredSize(new java.awt.Dimension(276, 260));

        javax.swing.GroupLayout MainLeftBottomLayout = new javax.swing.GroupLayout(MainLeftBottom);
        MainLeftBottom.setLayout(MainLeftBottomLayout);
        MainLeftBottomLayout.setHorizontalGroup(
            MainLeftBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        MainLeftBottomLayout.setVerticalGroup(
            MainLeftBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        MainLeft.add(MainLeftBottom, java.awt.BorderLayout.PAGE_END);

        Main.add(MainLeft, java.awt.BorderLayout.LINE_START);

        MainRight.setLayout(new java.awt.BorderLayout());
        Main.add(MainRight, java.awt.BorderLayout.CENTER);

        jPanel1.add(Main, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        frame = new BODY.login();
        frame.setVisible(true);
    }//GEN-LAST:event_lblLoginMouseClicked

    private void lblLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseExited
        lblLogin.setBackground(Color.white);
    }//GEN-LAST:event_lblLoginMouseExited

    private void lblLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseEntered
        lblLogin.setBackground(new Color(232, 243, 236));
    }//GEN-LAST:event_lblLoginMouseEntered

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        childPanel = new home();
        MainRight.removeAll();
        MainRight.add(childPanel);
        MainRight.validate();

        btnHome.setBackground(new Color(255, 255, 102));
        btnHome.setForeground(Color.black);
        btnHome.setFont(new Font("Dialog", Font.BOLD, 16));

        btnLearn.setBackground(new Color(12, 79, 46));
        btnLearn.setForeground(Color.white);
        btnLearn.setFont(new Font("Dialog", Font.BOLD, 18));

        btnQuiz.setBackground(new Color(12, 79, 46));
        btnQuiz.setForeground(Color.white);
        btnQuiz.setFont(new Font("Dialog", Font.BOLD, 18));

        panelHome.setBorder(BorderFactory.createLineBorder(Color.yellow));
        panelLearn.setBorder(BorderFactory.createLineBorder(Color.darkGray));
        panelQuiz.setBorder(BorderFactory.createLineBorder(Color.darkGray));

        btnQuanLy.setBackground(Color.white);
        btnQuanLy.setForeground(Color.black);
        btnQuanLy.setFont(new Font("Dialog", Font.PLAIN, 20));

        btnHuongDan.setBackground(Color.white);
        btnHuongDan.setForeground(Color.black);
        btnHuongDan.setFont(new Font("Dialog", Font.PLAIN, 20));
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnLearnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLearnMouseClicked
        childPanel = new Hoc(username);
        MainRight.removeAll();
        MainRight.add(childPanel);
        MainRight.validate();

        btnHome.setBackground(new Color(12, 79, 46));
        btnHome.setForeground(Color.white);
        btnHome.setFont(new Font("Dialog", Font.BOLD, 18));

        btnLearn.setBackground(new Color(255, 255, 102));
        btnLearn.setForeground(Color.black);
        btnLearn.setFont(new Font("Dialog", Font.BOLD, 16));

        btnQuiz.setBackground(new Color(12, 79, 46));
        btnQuiz.setForeground(Color.white);
        btnQuiz.setFont(new Font("Dialog", Font.BOLD, 18));

        panelHome.setBorder(BorderFactory.createLineBorder(Color.darkGray));
        panelLearn.setBorder(BorderFactory.createLineBorder(Color.yellow));
        panelQuiz.setBorder(BorderFactory.createLineBorder(Color.darkGray));

        btnQuanLy.setBackground(Color.white);
        btnQuanLy.setForeground(Color.black);
        btnQuanLy.setFont(new Font("Dialog", Font.PLAIN, 20));

        btnHuongDan.setBackground(Color.white);
        btnHuongDan.setForeground(Color.black);
        btnHuongDan.setFont(new Font("Dialog", Font.PLAIN, 20));
    }//GEN-LAST:event_btnLearnMouseClicked

    private void btnQuizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuizMouseClicked
        childPanel = new LamKiemtra(username);
        MainRight.removeAll();
        MainRight.add(childPanel);
        MainRight.validate();

        btnHome.setBackground(new Color(12, 79, 46));
        btnHome.setForeground(Color.white);
        btnHome.setFont(new Font("Dialog", Font.BOLD, 18));

        btnLearn.setBackground(new Color(12, 79, 46));
        btnLearn.setForeground(Color.white);
        btnLearn.setFont(new Font("Dialog", Font.BOLD, 18));

        btnQuiz.setBackground(new Color(255, 255, 102));
        btnQuiz.setForeground(Color.black);
        btnQuiz.setFont(new Font("Dialog", Font.BOLD, 16));

        panelHome.setBorder(BorderFactory.createLineBorder(Color.darkGray));
        panelLearn.setBorder(BorderFactory.createLineBorder(Color.darkGray));
        panelQuiz.setBorder(BorderFactory.createLineBorder(Color.yellow));

        btnQuanLy.setBackground(Color.white);
        btnQuanLy.setForeground(Color.BLACK);
        btnQuanLy.setFont(new Font("Dialog", Font.PLAIN, 20));

        btnHuongDan.setBackground(Color.white);
        btnHuongDan.setForeground(Color.BLACK);
        btnHuongDan.setFont(new Font("Dialog", Font.PLAIN, 20));
    }//GEN-LAST:event_btnQuizMouseClicked

    private void btnQuanLyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyMouseClicked
        childPanel = new build();
        MainRight.removeAll();
        MainRight.add(childPanel);
        MainRight.validate();

        btnQuanLy.setBackground(new Color(0, 153, 204));
        btnQuanLy.setForeground(Color.white);
        btnQuanLy.setFont(new Font("Dialog", Font.BOLD, 16));

        btnHuongDan.setBackground(new Color(245, 248, 250));
        btnHuongDan.setForeground(Color.BLACK);
        btnHuongDan.setFont(new Font("Dialog", Font.PLAIN, 18));

        btnHome.setBackground(new Color(12, 79, 46));
        btnHome.setForeground(Color.white);
        btnHome.setFont(new Font("Dialog", Font.BOLD, 18));

        btnLearn.setBackground(new Color(12, 79, 46));
        btnLearn.setForeground(Color.white);
        btnLearn.setFont(new Font("Dialog", Font.BOLD, 18));

        btnQuiz.setBackground(new Color(12, 79, 46));
        btnQuiz.setForeground(Color.white);
        btnQuiz.setFont(new Font("Dialog", Font.BOLD, 18));
    }//GEN-LAST:event_btnQuanLyMouseClicked

    private void btnHuongDanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuongDanMouseClicked
        childPanel = new HD();
        MainRight.removeAll();
        MainRight.add(childPanel);
        MainRight.validate();

        btnQuanLy.setBackground(Color.white);
        btnQuanLy.setForeground(Color.BLACK);
        btnQuanLy.setFont(new Font("Dialog", Font.PLAIN, 18));

        btnHuongDan.setBackground(new Color(0, 153, 204));
        btnHuongDan.setForeground(Color.WHITE);
        btnHuongDan.setFont(new Font("Dialog", Font.BOLD, 16));

        btnHome.setBackground(new Color(12, 79, 46));
        btnHome.setForeground(Color.white);
        btnHome.setFont(new Font("Dialog", Font.BOLD, 18));

        btnLearn.setBackground(new Color(12, 79, 46));
        btnLearn.setForeground(Color.white);
        btnLearn.setFont(new Font("Dialog", Font.BOLD, 18));

        btnQuiz.setBackground(new Color(12, 79, 46));
        btnQuiz.setForeground(Color.white);
        btnQuiz.setFont(new Font("Dialog", Font.BOLD, 18));
    }//GEN-LAST:event_btnHuongDanMouseClicked

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        lblLogout.setBackground(Color.white);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        //lblLogout.setBackground(new Color(232, 243, 236));
    }//GEN-LAST:event_lblLogoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel MainLeft;
    private javax.swing.JPanel MainLeftBottom;
    private javax.swing.JPanel MainLeftCenter;
    private javax.swing.JPanel MainLeftTop;
    private javax.swing.JPanel MainRight;
    private javax.swing.JPanel TopLeft;
    private javax.swing.JPanel TopRight;
    private BODY.Button.ButtonHome btnHome;
    private BODY.Button.ButtonHome btnHuongDan;
    private BODY.Button.ButtonHome btnLearn;
    private BODY.Button.ButtonHome btnQuanLy;
    private BODY.Button.ButtonHome btnQuiz;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLearn;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelLogout;
    private javax.swing.JPanel panelQuanLy;
    private javax.swing.JPanel panelQuiz;
    // End of variables declaration//GEN-END:variables
}
