/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BODY;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import user.Connect;

/**
 *
 * @author HP
 */
public class login extends javax.swing.JFrame {

    public login() {
        initComponents();
        setLocationRelativeTo(null);
        //setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelTaiKhoan = new javax.swing.JPanel();
        iconUsername = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        panelMatKhau = new javax.swing.JPanel();
        iconPassword = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        Bottom = new javax.swing.JPanel();
        btnLogin = new BODY.Button.ButtonLogin();
        lblQuenMatKhau = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblReg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 216, 224));

        Main.setBackground(new java.awt.Color(204, 216, 224));
        Main.setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(204, 216, 224));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBackground(new java.awt.Color(255, 255, 255));
        Title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("ĐĂNG NHẬP TÀI KHOẢN");
        Header.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 100));

        jSeparator1.setBackground(new java.awt.Color(0, 120, 255));
        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator1.setOpaque(true);
        Header.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 75, 190, 5));

        Main.add(Header, java.awt.BorderLayout.PAGE_START);

        Content.setBackground(new java.awt.Color(204, 216, 224));
        Content.setBorder(null);
        Content.setPreferredSize(new java.awt.Dimension(500, 280));
        Content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Tài khoản");
        Content.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 100, 35));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Mật khẩu");
        Content.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 125, 100, 35));

        panelTaiKhoan.setLayout(new java.awt.BorderLayout());

        iconUsername.setBackground(new java.awt.Color(153, 153, 153));
        iconUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/5402435_account_profile_user_avatar_man_icon.png"))); // NOI18N
        iconUsername.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        iconUsername.setOpaque(true);
        iconUsername.setPreferredSize(new java.awt.Dimension(40, 40));
        panelTaiKhoan.add(iconUsername, java.awt.BorderLayout.WEST);

        txtTaiKhoan.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTaiKhoan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelTaiKhoan.add(txtTaiKhoan, java.awt.BorderLayout.CENTER);

        Content.add(panelTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 340, 40));

        panelMatKhau.setLayout(new java.awt.BorderLayout());

        iconPassword.setBackground(new java.awt.Color(153, 153, 153));
        iconPassword.setForeground(new java.awt.Color(153, 153, 153));
        iconPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/7491947_ui_key_password_lock_security_icon.png"))); // NOI18N
        iconPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        iconPassword.setOpaque(true);
        iconPassword.setPreferredSize(new java.awt.Dimension(40, 40));
        panelMatKhau.add(iconPassword, java.awt.BorderLayout.WEST);

        txtMatKhau.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtMatKhau.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelMatKhau.add(txtMatKhau, java.awt.BorderLayout.CENTER);

        Content.add(panelMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 165, 340, 40));

        jCheckBox1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jCheckBox1.setText("Hiện mật khẩu");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        Content.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, 40));

        Main.add(Content, java.awt.BorderLayout.CENTER);

        Bottom.setBackground(new java.awt.Color(204, 216, 224));
        Bottom.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Bottom.setPreferredSize(new java.awt.Dimension(500, 220));
        Bottom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setText("ĐĂNG NHẬP");
        btnLogin.setToolTipText("");
        btnLogin.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        btnLogin.setRadius(50);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        Bottom.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 380, 50));

        lblQuenMatKhau.setFont(new java.awt.Font("Dialog", 3, 16)); // NOI18N
        lblQuenMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/7225775_arrow_login_icon.png"))); // NOI18N
        lblQuenMatKhau.setText("Quên mật khẩu ?");
        lblQuenMatKhau.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lblQuenMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuenMatKhauMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuenMatKhauMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuenMatKhauMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblQuenMatKhauMousePressed(evt);
            }
        });
        Bottom.add(lblQuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 100, 170, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 16)); // NOI18N
        jLabel5.setText("Bạn chưa có tài khoản ? Đăng ký");
        Bottom.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 250, 30));

        lblReg.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblReg.setForeground(new java.awt.Color(0, 0, 204));
        lblReg.setText("Tại đây");
        lblReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblRegMousePressed(evt);
            }
        });
        Bottom.add(lblReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 60, 30));

        Main.add(Bottom, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(Main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        StringBuilder sb = new StringBuilder();
        if (txtTaiKhoan.getText().equals("") && txtMatKhau.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Tài khoản và mật khẩu không được để trống!");
        } else {
            try {
                Connect a = new Connect();
                Connection conn = a.getConnection();
                String sql = "Select * from NguoiDung WHERE TaiKhoan=? and MatKhau=?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, txtTaiKhoan.getText());
                ps.setString(2, txtMatKhau.getText());
                ResultSet rs = ps.executeQuery();
                
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
                    GUI g = new GUI(txtTaiKhoan.getText());
                    g.setVisible(true); //để hiển thị màn hình form đăng nhập
                    setVisible(false); //thoát khỏi của sổ login
                } else {
                    JOptionPane.showMessageDialog(this, "Đăng nhập không thành công!");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            txtMatKhau.setEchoChar((char) 0);
        } else {
            txtMatKhau.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void lblRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegMouseClicked
        reg r = new reg();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblRegMouseClicked

    private void lblQuenMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMatKhauMouseClicked
        getPassword r = new getPassword();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblQuenMatKhauMouseClicked

    private void lblQuenMatKhauMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMatKhauMouseEntered
        lblQuenMatKhau.setForeground(new Color(234, 67, 53));
    }//GEN-LAST:event_lblQuenMatKhauMouseEntered

    private void lblQuenMatKhauMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMatKhauMouseExited
        lblQuenMatKhau.setForeground(Color.black);
    }//GEN-LAST:event_lblQuenMatKhauMouseExited

    private void lblQuenMatKhauMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMatKhauMousePressed
        lblQuenMatKhau.setForeground(Color.blue);
    }//GEN-LAST:event_lblQuenMatKhauMousePressed

    private void lblRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegMouseEntered
        lblReg.setForeground(new Color(234, 67, 53));
    }//GEN-LAST:event_lblRegMouseEntered

    private void lblRegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegMouseExited
        lblQuenMatKhau.setForeground(Color.blue);
    }//GEN-LAST:event_lblRegMouseExited

    private void lblRegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegMousePressed
        lblQuenMatKhau.setForeground(Color.black);
    }//GEN-LAST:event_lblRegMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bottom;
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Main;
    private javax.swing.JLabel Title;
    private BODY.Button.ButtonLogin btnLogin;
    private javax.swing.JLabel iconPassword;
    private javax.swing.JLabel iconUsername;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblQuenMatKhau;
    private javax.swing.JLabel lblReg;
    private javax.swing.JPanel panelMatKhau;
    private javax.swing.JPanel panelTaiKhoan;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables

    private void checkEmpty(StringBuilder sb) {
        if (txtTaiKhoan.getText().equals("")) {
            txtTaiKhoan.setBackground(Color.yellow);
            //JOptionPane.showMessageDialog(this, "MSSV CHƯA NHẬP!");
            sb.append("Tên đăng nhập không được bỏ trống!\n");
        } else {
            txtTaiKhoan.setBackground(Color.white);
        }
        if (txtMatKhau.getText().equals("")) {
            txtMatKhau.setBackground(Color.yellow);
            //JOptionPane.showMessageDialog(this, "HỌ TÊN CHƯA NHẬP!\n");
            sb.append("Mật khẩu không được bỏ trống!\n");
        } else {
            txtMatKhau.setBackground(Color.white);
        }
    }
}
