/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manegement.panelData;

import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class HD extends javax.swing.JPanel {

    private JPanel childPanel;

    public HD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Body = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Left = new javax.swing.JPanel();
        btnHoc = new javax.swing.JButton();
        btnKiemtra = new javax.swing.JButton();
        Center = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelContent = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        Body.setLayout(new java.awt.BorderLayout());

        Header.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Header.setPreferredSize(new java.awt.Dimension(1400, 100));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("HƯỚNG DẪN SỬ DỤNG PHẦN MỀM");
        Header.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 1396, 96));

        jSeparator1.setBackground(new java.awt.Color(0, 120, 255));
        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator1.setOpaque(true);
        Header.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 70, 200, 5));

        Body.add(Header, java.awt.BorderLayout.PAGE_START);

        Left.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(80, 80, 80, 80)));
        Left.setPreferredSize(new java.awt.Dimension(400, 780));
        Left.setRequestFocusEnabled(false);
        Left.setLayout(new java.awt.GridLayout(7, 0, 0, 20));

        btnHoc.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnHoc.setText("HỌC TỪ VỰNG");
        btnHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHocActionPerformed(evt);
            }
        });
        Left.add(btnHoc);

        btnKiemtra.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnKiemtra.setText("KIỂM TRA");
        btnKiemtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiemtraActionPerformed(evt);
            }
        });
        Left.add(btnKiemtra);

        Body.add(Left, java.awt.BorderLayout.LINE_START);

        Center.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Center.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(20, 50, 20, 50), javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thông tin chi tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 16)))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContent.setLayout(new java.awt.BorderLayout());
        jPanel1.add(panelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 93, 684, 607));

        Center.add(jPanel1, java.awt.BorderLayout.CENTER);

        Body.add(Center, java.awt.BorderLayout.CENTER);

        add(Body, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHocActionPerformed
        childPanel = new HDHoc();
        panelContent.removeAll();
        panelContent.add(childPanel);
        panelContent.validate();
    }//GEN-LAST:event_btnHocActionPerformed

    private void btnKiemtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiemtraActionPerformed
        childPanel = new HDKiemtra();
        panelContent.removeAll();
        panelContent.add(childPanel);
        panelContent.validate();
    }//GEN-LAST:event_btnKiemtraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Center;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Left;
    private javax.swing.JButton btnHoc;
    private javax.swing.JButton btnKiemtra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelContent;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
