/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manegement.panelData;

/**
 *
 * @author HP
 */
public class HDKiemtra extends javax.swing.JPanel {

    /**
     * Creates new form HD1
     */
    public HDKiemtra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HƯỚNG DẪN CÁCH ĐỂ KIỂM TRA TỪ VỰNG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 684, 87));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("1. Đầu tiên bắt buộc chọn cấp độ kiểm tra trước, có 3 mức (Dễ, Vừa và Khó).\n\n2. Tiếp theo lựa chọn chế độ kiểm tra (Trắc nghiệm hay Điền từ).\n     2.1. Trắc nghiệm:\n            2.1.1. Bấm chọn chủ đề để bắt đầu kiểm tra.\n            2.1.2. Hệ thống tiến hành tạo mã bài kiểm tra mới trong cơ sở dữ liệu và \nhiển thị form bài kiểm tra.\n            2.1.3. Bài kiểm tra có quy định về thời gian làm bài và số lượng câu hỏi \ntùy thuộc vào cấp độ đã chọn. Nếu hết thời gian form sẽ tự động đóng lại và tiến hành tổng hợp kết quả lưu vào cơ sở dữ liệu.\n            2.1.4. Bấm Next để chuyển đến câu hỏi tiếp theo và nút Submit để kết \nthúc bài làm.\n            2.1.5. Nếu muốn quay lại bấm vào dấu mũi tên quay lại để thoát form kiểm\ntra.\n     2.2. Điền từ:\n            2.2.1. Bấm chọn chủ đề để bắt đầu kiểm tra.\n            2.2.2. Hệ thống tiến hành tạo mã bài kiểm tra mới trong cơ sở dữ liệu và \nhiển thị form bài kiểm tra.\n            2.2.3. Bài kiểm tra có quy định về thời gian làm bài và số lượng câu hỏi \ntùy thuộc vào cấp độ đã chọn. Nếu hết thời gian form sẽ tự động đóng lại và tiến hành tổng hợp kết quả lưu vào cơ sở dữ liệu.\n\n3. Bấm Next để chuyển đến câu hỏi tiếp theo và nút Submit để kết thúc bài làm.\n\n4. Nếu muốn quay lại bấm vào dấu mũi tên quay lại để đóng form kiểm tra.\n\n");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 684, 520));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
