/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manegement.panelData;

import Manegement.Learn.bovacontrung;
import Manegement.Learn.dongvat;
import Manegement.Learn.hoctatca;
import Manegement.Learn.hoctatcaRand;
import Manegement.Learn.mausac;
import Manegement.Learn.raucu;
import Manegement.Learn.traicay;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import user.Connect;

/**
 *
 * @author HP
 */
public class Hoc extends javax.swing.JPanel {

    private JPanel childPanel;
    private JFrame frame;

    DefaultTableModel tbn = new DefaultTableModel();
    Connect a = new Connect();
    Connection con = a.getConnection();
    Statement st = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    String fPath = null;
    byte[] img_DATA;

    private String username;

    public Hoc(String username) {
        initComponents();
        this.username = username;
        getConnection();
        loadTest();
        Topic1();
        Topic2();
        Topic3();
        Topic4();
        Topic5();
        btnStart.setEnabled(false);
    }

    public void Topic1() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Vocabulary\\Animals\\Hamster.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(232, 130, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lblImage1.setIcon(image);
    }

    public void Topic2() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Vocabulary\\Bugs and insects\\Grasshopper.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(232, 130, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lblImage2.setIcon(image);
    }

    public void Topic3() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Vocabulary\\Colors\\Yellow.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(232, 130, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lblImage3.setIcon(image);
    }

    public void Topic4() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Vocabulary\\Fruits\\Apple.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(232, 130, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lblImage4.setIcon(image);
    }

    public void Topic5() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Vocabulary\\Vegetables\\Cabbage.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(232, 130, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lblImage5.setIcon(image);
    }

    public void getConnection() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=duan1;user=sa;password=sa2008");
            st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = st.executeQuery("Select * from TuVung where TenChuDe not in ('Random')");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            System.out.println(e.toString());
        }
    }

    public void loadTest() {
        try {
            rs.first();
            lblVocabulary.setText(rs.getString("TuVung"));
            byte[] img = rs.getBytes("HinhAnh");
            ImageIcon imgIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH));
            lblImg.setIcon(imgIcon);
            img_DATA = img;
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        Title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Vocabulary = new javax.swing.JPanel();
        lblPrevious = new javax.swing.JLabel();
        lblNext = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();
        lblVocabulary = new javax.swing.JLabel();
        Option = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        cbbCheDo = new javax.swing.JComboBox<>();
        Main = new javax.swing.JPanel();
        MainCenter = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTopic1 = new javax.swing.JLabel();
        lblImage1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTopic2 = new javax.swing.JLabel();
        lblImage2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTopic3 = new javax.swing.JLabel();
        lblImage3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTopic4 = new javax.swing.JLabel();
        lblImage4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblTopic5 = new javax.swing.JLabel();
        lblImage5 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        Header.setBorder(null);
        Header.setPreferredSize(new java.awt.Dimension(1400, 380));
        Header.setLayout(new java.awt.BorderLayout());

        Title.setBackground(new java.awt.Color(255, 255, 255));
        Title.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Title.setPreferredSize(new java.awt.Dimension(1400, 100));
        Title.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HỌC TỪ VỰNG");
        Title.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 1396, 96));

        jSeparator1.setBackground(new java.awt.Color(0, 120, 255));
        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator1.setOpaque(true);
        Title.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 70, 200, 5));

        Header.add(Title, java.awt.BorderLayout.PAGE_START);

        Vocabulary.setBackground(new java.awt.Color(204, 216, 224));
        Vocabulary.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Vocabulary.setPreferredSize(new java.awt.Dimension(700, 280));
        Vocabulary.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrevious.setBackground(new java.awt.Color(0, 102, 102));
        lblPrevious.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back_64px.png"))); // NOI18N
        lblPrevious.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblPrevious.setOpaque(true);
        lblPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPreviousMouseClicked(evt);
            }
        });
        Vocabulary.add(lblPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 115, 50, 50));

        lblNext.setBackground(new java.awt.Color(0, 102, 102));
        lblNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next_64px.png"))); // NOI18N
        lblNext.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNext.setOpaque(true);
        lblNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNextMouseClicked(evt);
            }
        });
        Vocabulary.add(lblNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 115, 50, 50));

        lblImg.setBackground(new java.awt.Color(255, 255, 255));
        lblImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImg.setOpaque(true);
        Vocabulary.add(lblImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 430, 220));

        lblVocabulary.setBackground(new java.awt.Color(255, 255, 255));
        lblVocabulary.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblVocabulary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVocabulary.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblVocabulary.setOpaque(true);
        Vocabulary.add(lblVocabulary, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 235, 430, 40));

        Header.add(Vocabulary, java.awt.BorderLayout.LINE_START);

        Option.setBackground(new java.awt.Color(204, 216, 224));
        Option.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Option.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStart.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnStart.setText("BẮT ĐẦU");
        btnStart.setPreferredSize(new java.awt.Dimension(170, 45));
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        Option.add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 250, 50));

        cbbCheDo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cbbCheDo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lựa chọn chế độ học", "Ngẫu nhiên", "Theo thứ tự" }));
        cbbCheDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbCheDoActionPerformed(evt);
            }
        });
        Option.add(cbbCheDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 219, 44));

        Header.add(Option, java.awt.BorderLayout.CENTER);

        add(Header, java.awt.BorderLayout.PAGE_START);

        Main.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Main.setLayout(new java.awt.BorderLayout());

        MainCenter.setBackground(new java.awt.Color(255, 255, 204));
        MainCenter.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 105, 20, 105));
        MainCenter.setLayout(new java.awt.GridLayout(2, 0, 35, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 200));
        jPanel1.setLayout(new java.awt.BorderLayout());

        lblTopic1.setBackground(new java.awt.Color(0, 51, 102));
        lblTopic1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTopic1.setForeground(new java.awt.Color(255, 255, 255));
        lblTopic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTopic1.setText("Chủ đề 1: Động vật");
        lblTopic1.setOpaque(true);
        lblTopic1.setPreferredSize(new java.awt.Dimension(41, 50));
        jPanel1.add(lblTopic1, java.awt.BorderLayout.PAGE_START);

        lblImage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage1MouseClicked(evt);
            }
        });
        jPanel1.add(lblImage1, java.awt.BorderLayout.CENTER);

        MainCenter.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 200));
        jPanel2.setLayout(new java.awt.BorderLayout());

        lblTopic2.setBackground(new java.awt.Color(0, 51, 102));
        lblTopic2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTopic2.setForeground(new java.awt.Color(255, 255, 255));
        lblTopic2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTopic2.setText("Chủ đề 2: Bọ và côn trùng");
        lblTopic2.setOpaque(true);
        lblTopic2.setPreferredSize(new java.awt.Dimension(41, 50));
        jPanel2.add(lblTopic2, java.awt.BorderLayout.PAGE_START);

        lblImage2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage2MouseClicked(evt);
            }
        });
        jPanel2.add(lblImage2, java.awt.BorderLayout.CENTER);

        MainCenter.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel3.setPreferredSize(new java.awt.Dimension(350, 200));
        jPanel3.setLayout(new java.awt.BorderLayout());

        lblTopic3.setBackground(new java.awt.Color(0, 51, 102));
        lblTopic3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTopic3.setForeground(new java.awt.Color(255, 255, 255));
        lblTopic3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTopic3.setText("Chủ đề 3: Màu sắc");
        lblTopic3.setOpaque(true);
        lblTopic3.setPreferredSize(new java.awt.Dimension(41, 50));
        jPanel3.add(lblTopic3, java.awt.BorderLayout.PAGE_START);

        lblImage3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage3MouseClicked(evt);
            }
        });
        jPanel3.add(lblImage3, java.awt.BorderLayout.CENTER);

        MainCenter.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel4.setPreferredSize(new java.awt.Dimension(350, 200));
        jPanel4.setLayout(new java.awt.BorderLayout());

        lblTopic4.setBackground(new java.awt.Color(0, 51, 102));
        lblTopic4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTopic4.setForeground(new java.awt.Color(255, 255, 255));
        lblTopic4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTopic4.setText("Chủ đề 4: Trái cây");
        lblTopic4.setOpaque(true);
        lblTopic4.setPreferredSize(new java.awt.Dimension(41, 50));
        jPanel4.add(lblTopic4, java.awt.BorderLayout.PAGE_START);

        lblImage4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage4MouseClicked(evt);
            }
        });
        jPanel4.add(lblImage4, java.awt.BorderLayout.CENTER);

        MainCenter.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel5.setPreferredSize(new java.awt.Dimension(350, 200));
        jPanel5.setLayout(new java.awt.BorderLayout());

        lblTopic5.setBackground(new java.awt.Color(0, 51, 102));
        lblTopic5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTopic5.setForeground(new java.awt.Color(255, 255, 255));
        lblTopic5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTopic5.setText("Chủ đề 5: Rau củ");
        lblTopic5.setOpaque(true);
        lblTopic5.setPreferredSize(new java.awt.Dimension(41, 50));
        jPanel5.add(lblTopic5, java.awt.BorderLayout.PAGE_START);

        lblImage5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImage5MouseClicked(evt);
            }
        });
        jPanel5.add(lblImage5, java.awt.BorderLayout.CENTER);

        MainCenter.add(jPanel5);

        Main.add(MainCenter, java.awt.BorderLayout.CENTER);

        add(Main, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void lblPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPreviousMouseClicked
        try {
            if (!rs.isFirst()) {
                rs.previous();
                lblVocabulary.setText(rs.getString("TuVung"));
                byte[] img = rs.getBytes("HinhAnh");
                ImageIcon imgIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH));
                lblImg.setIcon(imgIcon);
                img_DATA = img;
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_lblPreviousMouseClicked

    private void lblNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseClicked
        try {
            if (!rs.isLast()) {
                rs.next();
                lblVocabulary.setText(rs.getString("TuVung"));
                byte[] img = rs.getBytes("HinhAnh");
                ImageIcon imgIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH));
                lblImg.setIcon(imgIcon);
                img_DATA = img;
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_lblNextMouseClicked

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        if (cbbCheDo.getSelectedItem().toString().equals("Ngẫu nhiên")) {
            hoctatcaRand l = new hoctatcaRand();
            l.setVisible(true);
        } else if (cbbCheDo.getSelectedItem().toString().equals("Theo thứ tự")) {
            hoctatca l = new hoctatca();
            l.setVisible(true);
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void cbbCheDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbCheDoActionPerformed
        btnStart.setEnabled(true);
    }//GEN-LAST:event_cbbCheDoActionPerformed

    private void lblImage1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage1MouseClicked
        dongvat d = new dongvat();
        d.setVisible(true);
        lblTopic1.setBackground(Color.ORANGE);
        lblTopic1.setForeground(Color.black);
        
        lblTopic2.setBackground(new Color(0,51,102));
        lblTopic2.setForeground(Color.white);
        
        lblTopic3.setBackground(new Color(0,51,102));
        lblTopic3.setForeground(Color.white);
        
        lblTopic4.setBackground(new Color(0,51,102));
        lblTopic4.setForeground(Color.white);
        
        lblTopic5.setBackground(new Color(0,51,102));
        lblTopic5.setForeground(Color.white);
        
    }//GEN-LAST:event_lblImage1MouseClicked

    private void lblImage2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage2MouseClicked
        bovacontrung d = new bovacontrung();
        d.setVisible(true);
        
        lblTopic1.setBackground(new Color(0,51,102));
        lblTopic1.setForeground(Color.white);
        
        lblTopic2.setBackground(Color.ORANGE);
        lblTopic2.setForeground(Color.black);
        
        lblTopic3.setBackground(new Color(0,51,102));
        lblTopic3.setForeground(Color.white);
        
        lblTopic4.setBackground(new Color(0,51,102));
        lblTopic4.setForeground(Color.white);
        
        lblTopic5.setBackground(new Color(0,51,102));
        lblTopic5.setForeground(Color.white);
    }//GEN-LAST:event_lblImage2MouseClicked

    private void lblImage3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage3MouseClicked
        mausac d = new mausac();
        d.setVisible(true);
        
        lblTopic1.setBackground(new Color(0,51,102));
        lblTopic1.setForeground(Color.white);
        
        lblTopic2.setBackground(new Color(0,51,102));
        lblTopic2.setForeground(Color.white);
        
        lblTopic3.setBackground(Color.ORANGE);
        lblTopic3.setForeground(Color.black);
        
        lblTopic4.setBackground(new Color(0,51,102));
        lblTopic4.setForeground(Color.white);
        
        lblTopic5.setBackground(new Color(0,51,102));
        lblTopic5.setForeground(Color.white);
    }//GEN-LAST:event_lblImage3MouseClicked

    private void lblImage4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage4MouseClicked
        traicay d = new traicay();
        d.setVisible(true);
        
        lblTopic1.setBackground(new Color(0,51,102));
        lblTopic1.setForeground(Color.white);
        
        lblTopic2.setBackground(new Color(0,51,102));
        lblTopic2.setForeground(Color.white);
        
        lblTopic3.setBackground(new Color(0,51,102));
        lblTopic3.setForeground(Color.white);
        
        lblTopic4.setBackground(Color.ORANGE);
        lblTopic4.setForeground(Color.black);
        
        lblTopic5.setBackground(new Color(0,51,102));
        lblTopic5.setForeground(Color.white);
    }//GEN-LAST:event_lblImage4MouseClicked

    private void lblImage5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImage5MouseClicked
        raucu d = new raucu();
        d.setVisible(true);
        
        lblTopic1.setBackground(new Color(0,51,102));
        lblTopic1.setForeground(Color.white);
        
        lblTopic2.setBackground(new Color(0,51,102));
        lblTopic2.setForeground(Color.white);
        
        lblTopic3.setBackground(new Color(0,51,102));
        lblTopic3.setForeground(Color.white);
        
        lblTopic4.setBackground(new Color(0,51,102));
        lblTopic4.setForeground(Color.white);
        
        lblTopic5.setBackground(Color.ORANGE);
        lblTopic5.setForeground(Color.black);
    }//GEN-LAST:event_lblImage5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel MainCenter;
    private javax.swing.JPanel Option;
    private javax.swing.JPanel Title;
    private javax.swing.JPanel Vocabulary;
    private javax.swing.JButton btnStart;
    private javax.swing.JComboBox<String> cbbCheDo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblImage1;
    private javax.swing.JLabel lblImage2;
    private javax.swing.JLabel lblImage3;
    private javax.swing.JLabel lblImage4;
    private javax.swing.JLabel lblImage5;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblPrevious;
    private javax.swing.JLabel lblTopic1;
    private javax.swing.JLabel lblTopic2;
    private javax.swing.JLabel lblTopic3;
    private javax.swing.JLabel lblTopic4;
    private javax.swing.JLabel lblTopic5;
    private javax.swing.JLabel lblVocabulary;
    // End of variables declaration//GEN-END:variables
}
