/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manegement.panelData;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author HP
 */
public class home extends javax.swing.JPanel {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        LoadBG();
    }
    
    public void LoadBG() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Background\\20.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(1400, 880, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lblBg.setIcon(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblBg = new javax.swing.JLabel();

        setBorder(null);
        setMinimumSize(new java.awt.Dimension(1392, 872));
        setPreferredSize(new java.awt.Dimension(1392, 872));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Phần mềm hỗ trợ học Tiếng anh cho bé qua hình ảnh ");
        jLabel1.setPreferredSize(new java.awt.Dimension(1392, 872));
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        add(lblBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 880));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBg;
    // End of variables declaration//GEN-END:variables
}
