/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manegement.panelData;

import Manegement.classData.listLevel;
import Manegement.classData.listTopic;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import user.Connect;

/**
 *
 * @author HP
 */
public class Khac extends javax.swing.JPanel {

    DefaultTableModel tbn = new DefaultTableModel();
    Connect a = new Connect();
    Connection con = a.getConnection();
    Statement st = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public Khac() {
        initComponents();
        show_Topic();
        show_Level();
    }

    public ArrayList<listTopic> listTopic() {
        ArrayList<listTopic> ltTopic = new ArrayList<>();
        try {
            String url = "Select * from ChuDe";
            st = con.createStatement();
            rs = st.executeQuery(url);
            listTopic data;
            while (rs.next()) {
                data = new listTopic(rs.getString("TenChuDe"));
                ltTopic.add(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return ltTopic;
    }

    public ArrayList<listLevel> listLevel() {
        ArrayList<listLevel> ltLevel = new ArrayList<>();
        try {
            String url = "Select * from CapDo";
            st = con.createStatement();
            rs = st.executeQuery(url);
            listLevel data;
            while (rs.next()) {
                data = new listLevel(rs.getString("TenCapDo"));
                ltLevel.add(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return ltLevel;
    }

    public void show_Topic() {
        ArrayList<listTopic> list = listTopic();
        DefaultTableModel model = (DefaultTableModel) tblTopic.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        Object[] row = new Object[1];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getTopic();
            model.addRow(row);
        }
        JTableHeader Theader = tblTopic.getTableHeader();

        Theader.setBackground(new Color(59, 89, 152));
        Theader.setForeground(Color.black);

        Theader.setFont(new Font("Dialog", Font.BOLD, 17));
        ((DefaultTableCellRenderer) Theader.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);

        tblTopic.setFont(new Font("Dialog", Font.PLAIN, 17));
        tblTopic.setSelectionBackground(Color.DARK_GRAY);
        tblTopic.setSelectionForeground(Color.white);
    }

    public void show_Level() {
        ArrayList<listLevel> list = listLevel();
        DefaultTableModel model = (DefaultTableModel) tblLevel.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        Object[] row = new Object[1];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getLevel();
            model.addRow(row);
        }
        JTableHeader Theader = tblLevel.getTableHeader();

        Theader.setBackground(new Color(59, 89, 152));
        Theader.setForeground(Color.black);

        Theader.setFont(new Font("Dialog", Font.BOLD, 17));
        ((DefaultTableCellRenderer) Theader.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);

        tblLevel.setFont(new Font("Dialog", Font.PLAIN, 17));
        tblLevel.setSelectionBackground(Color.DARK_GRAY);
        tblLevel.setSelectionForeground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Body = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Left = new javax.swing.JPanel();
        LF = new javax.swing.JPanel();
        LFContent = new javax.swing.JPanel();
        txtTenChuDe = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenCapDo = new javax.swing.JTextField();
        LFOption = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        Right = new javax.swing.JPanel();
        RC = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLevel = new javax.swing.JTable();
        RB = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTopic = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        Body.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        Body.setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setPreferredSize(new java.awt.Dimension(700, 100));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DỮ LIỆU CHỦ ĐỀ VÀ CẤP ĐỘ");
        Header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1396, 100));

        jSeparator2.setBackground(new java.awt.Color(0, 120, 255));
        jSeparator2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator2.setOpaque(true);
        Header.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 300, 5));

        Body.add(Header, java.awt.BorderLayout.PAGE_START);

        Left.setPreferredSize(new java.awt.Dimension(700, 580));
        Left.setLayout(new java.awt.BorderLayout());

        LF.setBackground(new java.awt.Color(204, 216, 224));
        LF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        LF.setPreferredSize(new java.awt.Dimension(700, 280));
        LF.setLayout(new java.awt.BorderLayout());

        LFContent.setOpaque(false);
        LFContent.setPreferredSize(new java.awt.Dimension(500, 200));

        txtTenChuDe.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Tên chủ đề");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Tên cấp độ");

        txtTenCapDo.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N

        javax.swing.GroupLayout LFContentLayout = new javax.swing.GroupLayout(LFContent);
        LFContent.setLayout(LFContentLayout);
        LFContentLayout.setHorizontalGroup(
            LFContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LFContentLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(LFContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LFContentLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtTenCapDo, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LFContentLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtTenChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        LFContentLayout.setVerticalGroup(
            LFContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LFContentLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(LFContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LFContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenCapDo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(597, Short.MAX_VALUE))
        );

        LF.add(LFContent, java.awt.BorderLayout.CENTER);

        LFOption.setOpaque(false);
        LFOption.setPreferredSize(new java.awt.Dimension(200, 200));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 15);
        flowLayout1.setAlignOnBaseline(true);
        LFOption.setLayout(flowLayout1);

        btnAdd.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/34237_+_add_plus_icon.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.setPreferredSize(new java.awt.Dimension(160, 45));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        LFOption.add(btnAdd);

        btnSave.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/285657_floppy_guardar_save_icon.png"))); // NOI18N
        btnSave.setText("Lưu");
        btnSave.setPreferredSize(new java.awt.Dimension(160, 45));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        LFOption.add(btnSave);

        btnDelete.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/34218_add_cross_delete_exit_remove_icon.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.setPreferredSize(new java.awt.Dimension(160, 45));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        LFOption.add(btnDelete);

        btnReset.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/8542647_undo_back_icon.png"))); // NOI18N
        btnReset.setText("Làm sạch");
        btnReset.setPreferredSize(new java.awt.Dimension(160, 45));
        LFOption.add(btnReset);

        LF.add(LFOption, java.awt.BorderLayout.EAST);

        Left.add(LF, java.awt.BorderLayout.CENTER);

        Body.add(Left, java.awt.BorderLayout.WEST);

        Right.setBackground(new java.awt.Color(204, 216, 224));
        Right.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        Right.setLayout(new java.awt.BorderLayout(0, 20));

        RC.setBackground(new java.awt.Color(204, 216, 224));
        RC.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray), javax.swing.BorderFactory.createEmptyBorder(0, 20, 20, 20)), "DỮ LIỆU BẢNG CẤP ĐỘ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18)))); // NOI18N
        RC.setPreferredSize(new java.awt.Dimension(300, 380));
        RC.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tblLevel.setAutoCreateRowSorter(true);
        tblLevel.setBorder(null);
        tblLevel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "TÊN CẤP ĐỘ"
            }
        ));
        tblLevel.setRowHeight(30);
        tblLevel.setShowHorizontalLines(true);
        tblLevel.setShowVerticalLines(true);
        tblLevel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLevelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblLevel);

        RC.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        Right.add(RC, java.awt.BorderLayout.CENTER);

        RB.setBackground(new java.awt.Color(204, 216, 224));
        RB.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray), javax.swing.BorderFactory.createEmptyBorder(0, 20, 20, 20)), "DỮ LIỆU BẢNG CHỦ ĐỀ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18))); // NOI18N
        RB.setPreferredSize(new java.awt.Dimension(300, 380));
        RB.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tblTopic.setBorder(null);
        tblTopic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "TÊN CHỦ ĐỀ"
            }
        ));
        tblTopic.setRowHeight(30);
        tblTopic.setShowHorizontalLines(true);
        tblTopic.setShowVerticalLines(true);
        tblTopic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTopicMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTopic);

        RB.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        Right.add(RB, java.awt.BorderLayout.PAGE_END);

        Body.add(Right, java.awt.BorderLayout.CENTER);

        add(Body, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        btnAdd.setEnabled(false);
        dataNotEnabledButton();
        reset();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtTenChuDe.getText().equals("") && txtTenCapDo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không được bỏ trống!");
        } else {
            if (!txtTenChuDe.getText().equals("")) {
                try {
                    String url = "insert into ChuDe values (?)";
                    pst = con.prepareStatement(url);
                    pst.setString(1, txtTenChuDe.getText());
                    pst.executeUpdate();
                    DefaultTableModel model = (DefaultTableModel) tblTopic.getModel();
                    model.setRowCount(0);
                    show_Topic();
                    JOptionPane.showMessageDialog(null, "Lưu dữ liệu thành công.");
                    btnAdd.setEnabled(true);
                    dataEnabledButton();
                    reset();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
            if (!txtTenCapDo.getText().equals("")) {
                try {
                    String url = "insert into CapDo values (?)";
                    pst = con.prepareStatement(url);
                    pst.setString(1, txtTenCapDo.getText());
                    pst.executeUpdate();
                    DefaultTableModel model = (DefaultTableModel) tblLevel.getModel();
                    model.setRowCount(0);
                    show_Level();
                    JOptionPane.showMessageDialog(null, "Lưu dữ liệu thành công.");
                    btnAdd.setEnabled(true);
                    dataEnabledButton();
                    reset();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (txtTenChuDe.getText().equals("") && txtTenCapDo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Dữ liệu không được bỏ trống!");
        } else {
            if (!txtTenChuDe.getText().equals("")) {
                try {
                    pst = con.prepareStatement("Delete ChuDe where TenChuDe=?");
                    pst.setString(1, tblTopic.getValueAt(tblTopic.getSelectedRow(), 0).toString());
                    if (JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa?", "Confirm", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        pst.executeUpdate();
                        DefaultTableModel model = (DefaultTableModel) tblTopic.getModel();
                        model.setRowCount(0);
                        show_Topic();
                        JOptionPane.showMessageDialog(this, "Xóa thành công");
                    }
                    btnAdd.setEnabled(true);
                    dataEnabledButton();
                    reset();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
                }
            }
            else if (!txtTenCapDo.getText().equals("")) {
                try {
                    pst = con.prepareStatement("Delete ChuDe where TenCapDo=?");
                    pst.setString(1, tblLevel.getValueAt(tblLevel.getSelectedRow(), 0).toString());
                    if (JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa?", "Confirm", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        pst.executeUpdate();
                        DefaultTableModel model = (DefaultTableModel) tblLevel.getModel();
                        model.setRowCount(0);
                        show_Level();
                        JOptionPane.showMessageDialog(this, "Xóa thành công");
                    }
                    btnAdd.setEnabled(true);
                    dataEnabledButton();
                    reset();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
                }
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblLevelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLevelMouseClicked
        int i = tblLevel.getSelectedRow();
        TableModel model = tblLevel.getModel();

        txtTenCapDo.setText(model.getValueAt(i, 0).toString());

        dataNotEnabledButton();
        txtTenChuDe.setText("");
        txtTenChuDe.setEnabled(false);
    }//GEN-LAST:event_tblLevelMouseClicked

    private void tblTopicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTopicMouseClicked
        int i = tblTopic.getSelectedRow();
        TableModel model = tblTopic.getModel();

        txtTenChuDe.setText(model.getValueAt(i, 0).toString());

        dataNotEnabledButton();
        txtTenCapDo.setText("");
        txtTenCapDo.setEnabled(false);
    }//GEN-LAST:event_tblTopicMouseClicked

    public void dataEnabledButton() {
        btnAdd.setEnabled(true);
        btnSave.setEnabled(false);
        btnDelete.setEnabled(false);
        btnReset.setEnabled(false);
        txtTenChuDe.setEnabled(false);
        txtTenCapDo.setEnabled(false);
    }

    public void dataNotEnabledButton() {
        btnAdd.setEnabled(false);
        btnSave.setEnabled(true);
        btnDelete.setEnabled(true);
        btnReset.setEnabled(true);
        txtTenChuDe.setEnabled(true);
        txtTenCapDo.setEnabled(true);
    }

    public void reset() {
        txtTenChuDe.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel LF;
    private javax.swing.JPanel LFContent;
    private javax.swing.JPanel LFOption;
    private javax.swing.JPanel Left;
    private javax.swing.JPanel RB;
    private javax.swing.JPanel RC;
    private javax.swing.JPanel Right;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblLevel;
    private javax.swing.JTable tblTopic;
    private javax.swing.JTextField txtTenCapDo;
    private javax.swing.JTextField txtTenChuDe;
    // End of variables declaration//GEN-END:variables
}
