/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manegement.panelData;

import Manegement.Quiz.quizD1;
import Manegement.Quiz.quizK1;
import Manegement.Quiz.quizV1;
import Manegement.Quiz.testD1;
import Manegement.Quiz.testK1;
import Manegement.Quiz.testV1;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class LamKiemtra extends javax.swing.JPanel {

    private JPanel childPanel;
    private JFrame frame;

    private String username;
    private String TenCapDo = "";
    private String TenChuDe = "";
    private String HinhThuc = "";

    public LamKiemtra(String username) {
        initComponents();
        this.username = username;
        loadListTopic();
        lession1.setEnabled(false);
        lession2.setEnabled(false);
        lession3.setEnabled(false);
        cbxCHTN.setEnabled(false);
        cbxCHDT.setEnabled(false);
    }

    public void loadListTopic() {
        Topic1();
        Topic2();
        Topic3();
        Topic4();
        Topic5();
    }

    public void Topic1() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Vocabulary\\Animals\\Hamster.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(272, 122, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lblImgTopic1.setIcon(image);
    }

    public void Topic2() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Vocabulary\\Bugs and insects\\Grasshopper.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(272, 122, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lblImgTopic2.setIcon(image);
    }

    public void Topic3() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Vocabulary\\Colors\\Yellow.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(272, 122, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lblImgTopic3.setIcon(image);
    }

    public void Topic4() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Vocabulary\\Fruits\\Pineapple.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(272, 122, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lblImgTopic4.setIcon(image);
    }

    public void Topic5() {
        ImageIcon MyImage = new ImageIcon("C:\\Java-JSP\\duan9\\src\\img\\Vocabulary\\Vegetables\\Corn Cob.jpg");
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(272, 122, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lblImgTopic5.setIcon(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        cbxDe = new javax.swing.JCheckBox();
        cbxTB = new javax.swing.JCheckBox();
        cbxKho = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        cbxCHTN = new javax.swing.JCheckBox();
        cbxCHDT = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        ListTopic = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        AnimalTopic = new javax.swing.JPanel();
        lession1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lblImgTopic1 = new javax.swing.JLabel();
        lession2 = new javax.swing.JPanel();
        lbl2 = new javax.swing.JLabel();
        lblImgTopic2 = new javax.swing.JLabel();
        lession3 = new javax.swing.JPanel();
        lbl3 = new javax.swing.JLabel();
        lblImgTopic3 = new javax.swing.JLabel();
        lession4 = new javax.swing.JPanel();
        lbl4 = new javax.swing.JLabel();
        lblImgTopic4 = new javax.swing.JLabel();
        lession5 = new javax.swing.JPanel();
        lbl5 = new javax.swing.JLabel();
        lblImgTopic5 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPreferredSize(new java.awt.Dimension(1392, 872));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setPreferredSize(new java.awt.Dimension(1392, 100));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("KIỂM TRA TỪ VỰNG THEO CHỦ ĐỀ");
        Header.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1386, 100));

        jSeparator2.setBackground(new java.awt.Color(0, 120, 255));
        jSeparator2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSeparator2.setOpaque(true);
        Header.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 70, 250, 5));

        jPanel1.add(Header, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(240, 248, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(1392, 152));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxDe.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(cbxDe);
        cbxDe.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        cbxDe.setText("Cấp độ dễ");
        cbxDe.setAutoscrolls(true);
        cbxDe.setBorderPainted(true);
        cbxDe.setFocusPainted(false);
        cbxDe.setIconTextGap(20);
        cbxDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDeActionPerformed(evt);
            }
        });
        jPanel2.add(cbxDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 20, 120, 30));

        cbxTB.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(cbxTB);
        cbxTB.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        cbxTB.setText("Cấp độ vừa");
        cbxTB.setAutoscrolls(true);
        cbxTB.setBorderPainted(true);
        cbxTB.setFocusPainted(false);
        cbxTB.setIconTextGap(20);
        cbxTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTBActionPerformed(evt);
            }
        });
        jPanel2.add(cbxTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 20, 170, 30));

        cbxKho.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(cbxKho);
        cbxKho.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        cbxKho.setForeground(new java.awt.Color(51, 51, 51));
        cbxKho.setText("Cấp độ khó");
        cbxKho.setAutoscrolls(true);
        cbxKho.setBorderPainted(true);
        cbxKho.setFocusPainted(false);
        cbxKho.setIconTextGap(20);
        cbxKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxKhoActionPerformed(evt);
            }
        });
        jPanel2.add(cbxKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(921, 20, 120, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 204));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Chọn cấp độ bài kiểm tra");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 20, 220, 30));

        cbxCHTN.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(cbxCHTN);
        cbxCHTN.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        cbxCHTN.setText("Câu hỏi trắc nghiệm");
        cbxCHTN.setAutoscrolls(true);
        cbxCHTN.setBorderPainted(true);
        cbxCHTN.setFocusPainted(false);
        cbxCHTN.setIconTextGap(20);
        jPanel2.add(cbxCHTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 80, 180, 30));

        cbxCHDT.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(cbxCHDT);
        cbxCHDT.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        cbxCHDT.setText("Câu hỏi điền từ");
        cbxCHDT.setAutoscrolls(true);
        cbxCHDT.setBorderPainted(true);
        cbxCHDT.setFocusPainted(false);
        cbxCHDT.setIconTextGap(20);
        jPanel2.add(cbxCHDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(791, 80, 180, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 204));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Chọn cấp độ bài kiểm tra");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 80, -1, 30));

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        ListTopic.setBackground(new java.awt.Color(255, 255, 255));
        ListTopic.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ListTopic.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ListTopic.setPreferredSize(new java.awt.Dimension(1392, 575));
        ListTopic.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        jPanel3.setPreferredSize(new java.awt.Dimension(1392, 575));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AnimalTopic.setBackground(new java.awt.Color(255, 255, 204));
        AnimalTopic.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray), "DANH SÁCH BÀI KIỂM TRA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(0, 0, 0)))); // NOI18N
        AnimalTopic.setAutoscrolls(true);
        AnimalTopic.setPreferredSize(new java.awt.Dimension(1392, 275));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 30);
        flowLayout1.setAlignOnBaseline(true);
        AnimalTopic.setLayout(flowLayout1);

        lession1.setBackground(new java.awt.Color(255, 255, 255));
        lession1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray));
        lession1.setPreferredSize(new java.awt.Dimension(300, 200));
        lession1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl1.setBackground(new java.awt.Color(20, 17, 109));
        lbl1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Chủ đề 1: Động vật");
        lbl1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        lbl1.setOpaque(true);
        lbl1.setPreferredSize(new java.awt.Dimension(274, 50));
        lession1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 294, -1));

        lblImgTopic1.setBackground(new java.awt.Color(255, 255, 255));
        lblImgTopic1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblImgTopic1.setForeground(new java.awt.Color(102, 102, 102));
        lblImgTopic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgTopic1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgTopic1MouseClicked(evt);
            }
        });
        lession1.add(lblImgTopic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 54, 292, 142));

        AnimalTopic.add(lession1);

        lession2.setBackground(new java.awt.Color(255, 255, 255));
        lession2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray));
        lession2.setPreferredSize(new java.awt.Dimension(300, 200));
        lession2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl2.setBackground(new java.awt.Color(20, 17, 109));
        lbl2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("Chủ đề 2: Bọ và côn trùng");
        lbl2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        lbl2.setOpaque(true);
        lbl2.setPreferredSize(new java.awt.Dimension(274, 50));
        lession2.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 294, -1));

        lblImgTopic2.setBackground(new java.awt.Color(255, 255, 255));
        lblImgTopic2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblImgTopic2.setForeground(new java.awt.Color(102, 102, 102));
        lblImgTopic2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgTopic2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgTopic2MouseClicked(evt);
            }
        });
        lession2.add(lblImgTopic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 54, 292, 142));

        AnimalTopic.add(lession2);

        lession3.setBackground(new java.awt.Color(255, 255, 255));
        lession3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray));
        lession3.setPreferredSize(new java.awt.Dimension(300, 200));
        lession3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl3.setBackground(new java.awt.Color(20, 17, 109));
        lbl3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl3.setForeground(new java.awt.Color(255, 255, 255));
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setText("Chủ đề 3: Màu sắc");
        lbl3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        lbl3.setOpaque(true);
        lbl3.setPreferredSize(new java.awt.Dimension(274, 50));
        lession3.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 294, -1));

        lblImgTopic3.setBackground(new java.awt.Color(255, 255, 255));
        lblImgTopic3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblImgTopic3.setForeground(new java.awt.Color(102, 102, 102));
        lblImgTopic3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgTopic3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgTopic3MouseClicked(evt);
            }
        });
        lession3.add(lblImgTopic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 54, 292, 142));

        AnimalTopic.add(lession3);

        lession4.setBackground(new java.awt.Color(255, 255, 255));
        lession4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray));
        lession4.setPreferredSize(new java.awt.Dimension(300, 200));
        lession4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl4.setBackground(new java.awt.Color(20, 17, 109));
        lbl4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl4.setForeground(new java.awt.Color(255, 255, 255));
        lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl4.setText("Chủ đề 4: Trái cây");
        lbl4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        lbl4.setOpaque(true);
        lbl4.setPreferredSize(new java.awt.Dimension(274, 50));
        lession4.add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 294, -1));

        lblImgTopic4.setBackground(new java.awt.Color(255, 255, 255));
        lblImgTopic4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblImgTopic4.setForeground(new java.awt.Color(102, 102, 102));
        lblImgTopic4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgTopic4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgTopic4MouseClicked(evt);
            }
        });
        lession4.add(lblImgTopic4, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 54, 292, 142));

        AnimalTopic.add(lession4);

        lession5.setBackground(new java.awt.Color(255, 255, 255));
        lession5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.darkGray));
        lession5.setPreferredSize(new java.awt.Dimension(300, 200));
        lession5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl5.setBackground(new java.awt.Color(20, 17, 109));
        lbl5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl5.setForeground(new java.awt.Color(255, 255, 255));
        lbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl5.setText("Chủ đề 4: Trái cây");
        lbl5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        lbl5.setOpaque(true);
        lbl5.setPreferredSize(new java.awt.Dimension(274, 50));
        lession5.add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 294, -1));

        lblImgTopic5.setBackground(new java.awt.Color(255, 255, 255));
        lblImgTopic5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblImgTopic5.setForeground(new java.awt.Color(102, 102, 102));
        lblImgTopic5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgTopic5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgTopic5MouseClicked(evt);
            }
        });
        lession5.add(lblImgTopic5, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 54, 292, 142));

        AnimalTopic.add(lession5);

        jPanel3.add(AnimalTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 1292, 530));

        ListTopic.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(ListTopic, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public void checkboxQuestion() {
        if (cbxDe.isSelected() == true || cbxTB.isSelected() == true || cbxKho.isSelected() == true) {
            cbxCHTN.setEnabled(true);
            cbxCHDT.setEnabled(true);
        }
    }

    private void cbxDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDeActionPerformed
        checkboxQuestion();
    }//GEN-LAST:event_cbxDeActionPerformed

    private void cbxTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTBActionPerformed
        checkboxQuestion();
    }//GEN-LAST:event_cbxTBActionPerformed

    private void cbxKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxKhoActionPerformed
        checkboxQuestion();
    }//GEN-LAST:event_cbxKhoActionPerformed

    private void lblImgTopic1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgTopic1MouseClicked
        TenChuDe = "Animals";
        lbl1.setBackground(Color.orange);
        lbl2.setBackground(new Color(20,17,109));
        lbl3.setBackground(new Color(20,17,109));

        duLieuKiemTra();
    }//GEN-LAST:event_lblImgTopic1MouseClicked

    private void duLieuKiemTra() throws HeadlessException {
        if (cbxDe.isSelected() == false && cbxKho.isSelected() == false && cbxTB.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "Xin hãy chọn cấp độ!");
        } else if (cbxDe.isSelected() == true || cbxKho.isSelected() == true || cbxTB.isSelected() == true) {
            if (cbxCHTN.isSelected() == false && cbxCHDT.isSelected() == false) {
                JOptionPane.showMessageDialog(this, "Xin hãy chọn loại câu hỏi!");
            } else if (cbxCHTN.isSelected() == true || cbxCHDT.isSelected() == true) {
                if (cbxCHTN.isSelected() == true) {
                    HinhThuc = "Trắc nghiệm";
                    if (cbxDe.isSelected() == true) {                                   //Trắc nghiệm cấp độ dễ chủ đề động vật
                        TenCapDo = "Dễ";
                        
                        testD1 q = new testD1(username, TenCapDo, TenChuDe, HinhThuc);
                        q.setVisible(true);
                    } else if (cbxTB.isSelected() == true) {                            //Trắc nghiệm cấp độ vừa chủ đề động vật
                        TenCapDo = "Vừa";
                        
                        testV1 q = new testV1(username, TenCapDo, TenChuDe, HinhThuc);
                        q.setVisible(true);
                    } else if (cbxKho.isSelected() == true) {                           //Trắc nghiệm cấp độ khó chủ đề động vật
                        TenCapDo = "Khó";
                        
                        testK1 q = new testK1(username, TenCapDo, TenChuDe, HinhThuc);
                        q.setVisible(true);
                    }
                } else if (cbxCHDT.isSelected() == true) {
                    HinhThuc = "Điền từ";
                    if (cbxDe.isSelected() == true) {                                   //Điền từ cấp độ dễ chủ đề động vật
                        TenCapDo = "Dễ";
                        
                        quizD1 q = new quizD1(username, TenCapDo, TenChuDe, HinhThuc);
                        q.setVisible(true);
                    } else if (cbxTB.isSelected() == true) {                            //Điền từ cấp độ vừa chủ đề động vật
                        TenCapDo = "Vừa";
                        
                        quizV1 q = new quizV1(username, TenCapDo, TenChuDe, HinhThuc);
                        q.setVisible(true);
                    } else if (cbxKho.isSelected() == true) {                           //Điền từ cấp độ khó chủ đề động vật
                        TenCapDo = "Khó";
                        
                        quizK1 q = new quizK1(username, TenCapDo, TenChuDe, HinhThuc);
                        q.setVisible(true);
                    }
                }
            }
        }
    }

    private void lblImgTopic2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgTopic2MouseClicked
        TenChuDe = "Bugs and insects";
        lbl1.setBackground(new Color(20,17,109));
        lbl2.setBackground(Color.orange);
        lbl3.setBackground(new Color(20,17,109));

        duLieuKiemTra();
    }//GEN-LAST:event_lblImgTopic2MouseClicked

    private void lblImgTopic3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgTopic3MouseClicked
        TenChuDe = "Colors";
        lbl1.setBackground(new Color(20,17,109));
        lbl2.setBackground(new Color(20,17,109));
        lbl3.setBackground(Color.orange);

        duLieuKiemTra();
    }//GEN-LAST:event_lblImgTopic3MouseClicked

    private void lblImgTopic4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgTopic4MouseClicked
        TenChuDe = "Fruits";
        lbl1.setBackground(new Color(20,17,109));
        lbl2.setBackground(new Color(20,17,109));
        lbl3.setBackground(new Color(20,17,109));
        lbl4.setBackground(Color.orange);

        duLieuKiemTra();
    }//GEN-LAST:event_lblImgTopic4MouseClicked

    private void lblImgTopic5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgTopic5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImgTopic5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AnimalTopic;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel ListTopic;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox cbxCHDT;
    private javax.swing.JCheckBox cbxCHTN;
    private javax.swing.JCheckBox cbxDe;
    private javax.swing.JCheckBox cbxKho;
    private javax.swing.JCheckBox cbxTB;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lblImgTopic1;
    private javax.swing.JLabel lblImgTopic2;
    private javax.swing.JLabel lblImgTopic3;
    private javax.swing.JLabel lblImgTopic4;
    private javax.swing.JLabel lblImgTopic5;
    private javax.swing.JPanel lession1;
    private javax.swing.JPanel lession2;
    private javax.swing.JPanel lession3;
    private javax.swing.JPanel lession4;
    private javax.swing.JPanel lession5;
    // End of variables declaration//GEN-END:variables
}
